I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 282, in script
    python:
ScriptError: could not find label 'credits'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-8.3.7-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-8.3.7-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Applications/renpy-8.3.7-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/Applications/renpy-8.3.7-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 282, in script
    python:
  File "/Applications/renpy-8.3.7-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'credits'.

macOS-15.4.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
ArchivesFinal 1.0
Wed May  7 16:09:24 2025
